# all.yml
# Editble main settings for defining the installed MCP server's config file.

---

mcp_server_name: "Box_1" # change as desired (recommend to match name used client side for this box)
mcp_server_port: 9000 # default port for server
mcp_server_path: "/mcp" # default for URL
mcp_auth_token: "paste-here" # :~$ openssl rand -hex 32, then paste result here
mcp_service_user: mcp # names unprivleged user account that runs the server
pipx_home: /opt/pipx # pipx stores venvs for packages here
pipx_bin_dir: /user/local/bin # pipx links the server executable here
