# playbook.yaml
# The Ansible playbook. This file activates the roles that configure the host machine.

---

- name: Verify target node OS is supported
  hosts: mcp_hosts
  roles:
  - role: os_check
    tags: os_check

- name: Configure host with mcp-server-remote behind nginx reverse proxy
  hosts: mcp_hosts
  become: true # tasks run via root 'sudo' access
  roles:
    - role: nginx
      tags: nginx
    - role: mcp_server
      tags: mcp_server
